README.md
Use virtualenv instead of virtualenv wrapper. Make it clear where ansible runs, and that package managers generally have old, unsuitable versions of ansible
=> Improve quick start documentation

ansible/group_vars/all, ansible/roles/dns-dhcp/tasks/main.yml, ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2, ansible/roles/network-interfaces/defaults/main.yml, ansible/roles/network-interfaces/templates/etc_network_interfaces.j2
Replace direct references to wlan with references to the client-facing interface. This is a step towards abstracting the client-facing network from the wlan interface so it's easier to test, and easier to drop in a bluetooth PAN as an alternative to wifi, if we go down that path.
=> Parametrise client-facing interface (was wlan0)

.gitignore, .travis.yml, ci/script_run_on_non_pull_requests.sh, ci/tests/test_biblebox_static.py, requirements.txt
Introducing selenium, which will allow us to do automated browser tests during CI.
Initial tests are really about getting the framework in place, but there is a little bit of value for making sure that we redirect when accessing by hostname. Once the interface settles down we can add more tests, including tests for workflows.
=> Initial site tests

.travis.yml, ansible/roles/webserver-content/tasks/main.yml
Fixes problems that occur because the name of the server in the inventory (e.g. `default` for vagrant) isn't the same as the hostname itself. Required whitelisting a lint check.
=> Remove synchronise module

ansible/group_vars/all, ansible/roles/biblebox-pi/meta/main.yml, ansible/roles/sample-content/defaults/main.yml, ansible/roles/sample-content/tasks/main.yml, ansible/roles/usb-content/tasks/main.yml, ansible/roles/webserver-content/tasks/main.yml, tests/test_biblebox_static.py
@furnox is going to integrate the client side connect box interface (that was developed at the Boise hack). This prepares for that by:
* Removing the old biblebox interface
* Restructuring the web root to simplify the nginx config
* Exposing the contents of the USB drive as UTF-8 encoded json (per the nginx-autoindex module)
* Adding some sample content so we can see UTF-8 filenames, including arabic so we have a RtL example
=> Prepare for Connectbox interface

ansible/roles/dns-dhcp/tasks/main.yml, ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2
Fixed by adding /etc/hosts entry and answering queries with addresses on the querying interface.
Confirmed that tests were failing, and now pass. Our test cases can't catch this in CI yet, as the tests are not yet using the DNS provided by the pi. The move to terraform allows us to setup a second machine in CI and query and get DHCP over a private network, so will ultimately be a part of our test suite.
=> Fix broken wifi DNS

ansible/roles/sample-content/tasks/main.yml
@furnox @kldavis4 - I’ve moved the sample content repo to the new organisation, so you’ll need to pull in this change to any branches you’re working on if you want the playbook to run successfully.
=> Sample content now lives in the connectbox organisation

ansible/roles/bootstrap/tasks/main.yml
- Use ansible_lsb["id"] instead of ansible_distribution as raspbian and
debian jessie are both set to "Debian"
- Move openresolv installation after activation of jessie-backports, as it’s only available there.
=> Fix incorrect ordering and os conditional for debian

Vagrantfile, ansible/roles/connectbox-pi/defaults/main.yml, ansible/roles/connectbox-pi/handlers/main.yaml, ansible/roles/connectbox-pi/tasks/main.yml, ci/script_run_on_non_pull_requests.sh, docs/deployment.md
Overrideable by ansible variables (commandline, inventory or otherwise) to prevent disabling. sshd is not disabled in Vagrantfile or in CI runs. Documentation added.
Given this is a disruptive workflow change (albeit a documented one), I wanted to get input before merging. @kldavis4 @matheweis , any comments?
=> Disable sshd by default after playbook run

ansible/group_vars/orange_pi_zero, ansible/roles/network-interfaces/tasks/main.yml, ansible/roles/network-interfaces/templates/etc_network_interfaces.j2, ansible/roles/wifi-ap/defaults/main.yml, ansible/roles/wifi-ap/templates/hostapd.conf.j2
This PR is for the changes needed to get ConnectBox up and running on the OrangePi Zero (and probably most other Armbian based devices as well...)
The changes include:
1f118c5 - Using dhcp to configure eth0. Not sure how dhcp was working on RPi before, but Armbian was not having the "inet manual" approach. Changing this to the usual dhcp configured method seems to work fine on both Armbian and Debain/RPi
867baca, 4cd62fe, da78487 - NetworkManager does not play nice with hostapd. At best the wlan0 device could be excluded manually via a [keyfile] unmanaged-devices=... config, but since NM wasn't buying us anything we decided to remove it entirely. Since RPi didn't have it to begin with, it made sense to remove NM entirely any time it was found to be installed.
bd4f0c9 - OrangePi Zero …
=> Changes needed for OrangePi Zero

Vagrantfile, ansible/group_vars/armbian, ansible/group_vars/raspbian, ansible/inventory.example, ansible/roles/bootstrap/tasks/main.yml, ansible/roles/connectbox-pi/defaults/main.yml, ansible/roles/connectbox-pi/handlers/main.yaml, ansible/roles/connectbox-pi/tasks/main.yml, ci/script_run_on_non_pull_requests.sh, docs/deployment.md, docs/development.md
Fixes #74 
- Lock user account by default at the end of the playbook run
- Provide a mechanism that prevents account locking if a password hash is provided
- Introduce group_vars for armbian and raspbian and change example inventory to introduce required structure
- Change mechanism for disabling and stopping sshd at the end of the playbook run (no functional change, though)
- Add supporting doco
This is an invasive change, so I’d like input, please.
@kldavis4 @matheweis you’ll need to update your inventory files to contain the changes in the inventory.example if you’re going to run this branch of the playbook (indeed, you’ll need those changes once this merges anyway)
@matheweis , would you mind running this against your OPi to confirm that it disables the default account unless a …
=> Disable user accounts with insecure default passwords

ansible/roles/dns-dhcp/files/etc_default_dnsmasq, ansible/roles/dns-dhcp/handlers/main.yml, ansible/roles/dns-dhcp/tasks/main.yml
- specifying resolvconf=NO in /etc/resolvconf.conf meant that
/etc/resolv.conf was unmanaged and not even updated by dhclient which
meant that moving a device to a new network (or using an image
generated on a different network) caused DNS to break. Now we don't
need to bludgeon openresolv so that it doesn't touch /etc/resolv.conf
and we have a setup that respects dhclient
=> Make openresolv and dnsmasq play nicely together

ansible/group_vars/raspbian, ansible/roles/bootstrap/defaults/main.yml, ansible/roles/bootstrap/tasks/main.yml
The Debian Jessie-backports repo is armhf but compilied for ARMv7+ and
is unusable on the Pi Zero family so we introduce a repo that we
manage that provides just the packages we need from jessie-backports
compiled with the Raspbian toolchain as armhf for ARMv6+
=> Use connectbox jessie-backports repo for Raspbian

ansible/group_vars/all, ansible/roles/webserver-content/files/hotspot-detect.html, ansible/roles/webserver-content/tasks/main.yml, tests/test_connectbox_static.py
Yosemite and later have a different captive portal check to their
older MacOS brethren, so we need to add support for it.
This removes some user-agent logic from the nginx default server
that is no longer necessary. Previously the default server and the
connectbox server stanzas were combined, so we wanted to check the
useragent before responding with the magic captive portal responses
but now that it's separate, we don't have any risk of clashing with
a legit connectbox content request. This means we don't need the
user agent check. This meant that we could remove a negative test,
though we also added a test for Yosemite captive portal behaviour.
=> Fix MacOS Yosemite captive portal behaviour

ansible/roles/bootstrap/handlers/main.yml, ansible/roles/bootstrap/tasks/main.yml
This bug is transient, but has not reappeared for deploys done with this branch, so let’s merge.
=> Workaround log2ram armbian bug

CHANGELOG.md, ansible/roles/sample-content/tasks/main.yml
This is to help with throughput testing, and they are only created
when sample content is deployed
=> Create 10MB and 100MB test files in sample-content

ansible/group_vars/all, ansible/roles/connectbox-pi/tasks/main.yml, ansible/roles/connectbox-pi/templates/access-log-analyzer.conf.j2, ansible/roles/connectbox-pi/templates/access_log_analyzer.conf.j2, ansible/roles/connectbox-pi/templates/logrotate.hourly.conf.j2
Integrates access-log-analyzer script into connectbox-pi
Hooks into connectbox log rotate
Splits connectbox nginx access/error logs into a separate log directory to allow hourly policy to be applied
=> Access log analyzer integration

.travis.yml, ci/main.tf, ci/outputs.tf, ci/script_run_on_non_pull_requests.sh, ci/variables.tf
Auto-create DNS records for CI test instance, which avoids munging /etc/hosts on the build machine. Prep for Ubuntu CI machine.
=> Run CI on container-based infrastructure

ansible/group_vars/rt5372, ansible/group_vars/rtl8192cu
I incorrectly added rtl8192cu params as rt5372. Corrected now. Related to #120
=> Correct rt5372 ht_capab parameters

html/admin/api.php
Armbian and Raspbian set the locale appropriately, but the official
Ubuntu AMI that we'll use in #131 does not, which means that
escapeshellcmd strips out unicode characters, which is problematic
given we explicitly test setting SSIDs containing unicode strings (specifically, test32CharacterUnicodeSSIDSet is failing on the Ubuntu AMI without this change)
I don't think it's a problem to set this in the script, given we
control the connectbox environment and are shipping the device
with LC_CTYPE="en_US.UTF-8"  (it'd be LC_CTYPE="en_GB.UTF-8" if we
shipped a raspbian device), and both of those locales would allow
unicode characters through.
I don’t really know what I’m doing with PHP, so please correct me if this is inappropriate.
=> Set the locale in the admin api

ansible/roles/bootstrap/tasks/main.yml
(Doesn’t apply to virtualised installs, as their wlan interfaces are always faked anyway)
Fixes #122
=> Use old-style interface names for predictability across installations

Vagrantfile
* Reduce VM memory because our target deployments have less RAM.
* Swap host and domain for provisioned VMs to make it easier to manage a DNS domain with multiple connectboxes (e.g. rpi3.connectbox, ubuntu-vagrant.connectbox, neo.connectbox)
Have confirmed that the reduced memory doesn’t impact performance.
Wanted to check with you re: the DNS change in case it would cause a problem for you.
=> Provision 512mb VMs. Swap host+domain for VMs

ansible/group_vars/all, ansible/roles/connectbox-pi/meta/main.yml, ansible/roles/dns-dhcp/handlers/main.yml, ansible/roles/dns-dhcp/meta/main.yml, ansible/roles/dns-dhcp/tasks/main.yml, ansible/roles/network-interfaces/defaults/main.yml, ansible/roles/network-interfaces/templates/etc_network_interfaces.j2
dnsmasq is now started (and stopped) as a part of the ifup/ifdown
sequence for wlan0 based on solution by @matheweis 
Fixes #121
=> Fix dnsmasq startup ordering

ansible/roles/bootstrap/tasks/main.yml, ansible/site.yml
Also register a machine_type variable that contains the model of device
for machines running kernel 4.x (those that use fdt)
Fixes: #129
=> Activate internal USB ports on NanoPi NEO

ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2
> For DHCPv4, it changes the behaviour from strict RFC compliance so that DHCP requests on unknown leases from unknown hosts are not ignored. This allows new hosts to get a lease without a tedious timeout under all circumstances. It also allows dnsmasq to rebuild its lease database without each client needing to reacquire a lease, if the database is lost.
From: http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
All those things are good.
=> Tell dnsmasq to be authoritative for it's dhcp ranges

ansible/group_vars/ar9271, ansible/group_vars/pine64, ansible/group_vars/raspberry_pi_3, ansible/group_vars/raspberry_pi_zero_w, ansible/group_vars/rt5370, ansible/group_vars/rt5372, ansible/group_vars/rtl8192cu, ansible/roles/wifi-ap/defaults/main.yml, ansible/roles/wifi-ap/templates/hostapd.conf.j2
The choice to support 802.11g is a hangover from very early days. Remove the choice as we don’t need it.
=> Only support 802.11n adapters

ansible/group_vars/all
Had an issue with connecting to Connectbox from Linux desktop (Ubuntu 16.04).  
Once the Linux desktop had connected to the connectbox wireless network, it was issued an IP address.  Opening a browser and typing in any URL did not return a webpage, and would result in a timeout.  
Further research (Wireshark) determined that the following was happening.  The Browser (Chrome or Firefox) was correctly looking up the hostname using DNS.  DNS returned the IP address of connectbox (10.129.0.1).  The browser requested page HTTP://10.129.0.1, and was given a HTTP redirect to HTTP://connectbox.local.  Linux believed that this hostname was local, so a request was sent out over port 5353 (mDNS) to find the IP address, and did not receive a response, since mDNS is not configured in Avahi.  The …
=> Changed hostname from connectbox.local to connectbox

ansible/group_vars/generic_wifi_adapter, ansible/roles/wifi-ap/defaults/main.yml, docs/deployment.md
Create a generic configuration for use via ansible group_vars, and add some supporting docs.
Fixes #120
=> Default to rt5372 wifi configuration

html/admin/css/style.css, html/admin/js/connectbox-ui.js
On ssid update, the user is prompted to select the new ssid before continuing. A channel update will retry on error until the update is successful. The hostname dialog indicates the change was made and then redirects when the user clicks ok.
=> Fix #156 - Modify update logic to handle network changes

ansible/group_vars/all, ansible/roles/network-interfaces/templates/etc_network_interfaces.j2, ansible/roles/wifi-ap/defaults/main.yml, ansible/roles/wifi-ap/tasks/main.yml, ansible/roles/wifi-ap/templates/etc_default_crda.j2, ansible/roles/wifi-ap/templates/hostapd.conf.j2, ansible/roles/wifi-ap/templates/set_wifi_country_code.sh.j2
The world regulatory domain (00) is unnecessarily restrictive in
terms of channel selection and tx-power. We can infer the local
regulatory domain by looking at beacon frames from local access
points before bringing up the interface and hostapd.
An override is available by setting the REGDOMAIN in /etc/default/crda
(if ansible-playbook runs are involved, set wireless_country_code in
the ansible-playbook arguments)
=> Set wifi regdomain from sniffed AP beacon frames

html/admin/index.html
As our wifi interfaces run at max-power, as defined by the
regulatory domain, and there's no clear use-case for reducing
power, there's no need to expose setting txpower.
OK'ed by @geodirk
Fixes #40
=> Remove txpower menu entry from admin interface

ansible/roles/nginx/templates/connectbox_icon-only.conf.j2
When an initial setup was producing empty index responses (probably due to a solved error), Android appeared to be caching those empty index responses. As we do not set any expiry or cache control headers, this was causing ongoing problems. We (still) do not want to expire content.
FYI: @kldavis4 
Before:
```
$ curl -I http://neo.connectbox/content/
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Fri, 15 Sep 2017 22:50:21 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
$ curl -I http://neo.connectbox/content/Help/
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Fri, 15 Sep 2017 22:50:29 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
$ curl -I http://neo.connectbox/content/Help/help.txt
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Fri, 15 Sep 2017 …
```
=> Never cache autoindex responses

ansible/group_vars/armbian, ansible/group_vars/ubuntu, ansible/roles/bootstrap/defaults/main.yml, ansible/roles/bootstrap/tasks/main.yml
We’ll manage updates separately, and these services interfere with package installation during image creation.
=> Stop all automated apty services

html/admin/index.html, html/admin/js/connectbox-ui.js
The valid channel list is conservative, but will be valid for all
regulatory domains, but ultimately we should retrieve the valid
channels from the API, so that we can include channels that are
valid for the current regulatory domain.
Fixes #165 (even though someone could still brick the box using the API directly, that’s not an important use-case at this stage)
I’m not sure whether my use of `$('#input_channel')[0].selectedIndex` is appropriate. I was surprised that looking up an element by ID returned a list, but I’m in unfamiliar territory so wanted to call it out as potentially suspect.
=> Constrain channel to valid values in the UI

ansible/roles/bootstrap/tasks/main.yml
Also remove unnecessary block around stopping of apt services
Serves as a workaround for #149 and #214
=> Pin kernel and dtb packages to prevent upgrade

CHANGELOG.md, ansible/roles/bootstrap/tasks/main.yml
We mark the packages as held using `apt-mark`. We do a final upgrade with `aptitude safe-upgrade` and even though `aptitude` is supposed to honour the holds, it doesn’t because it seems the first invocation of aptitude wipes the marks.
e.g.
```
root@nanopineo:~# apt-mark showholds
root@nanopineo:~# apt-mark hold linux-dtb-dev-sun8i linux-image-dev-sun8i linux-u-boot-nan
opineo-dev
linux-dtb-dev-sun8i set on hold.
linux-image-dev-sun8i set on hold.
linux-u-boot-nanopineo-dev set on hold.
root@nanopineo:~# apt-mark showholds
linux-dtb-dev-sun8i
linux-image-dev-sun8i
linux-u-boot-nanopineo-dev
root@nanopineo:~# aptitude
root@nanopineo:~# apt-mark showholds
root@nanopineo:~#
```
=> Preserve usbhost1 dtb overlay

README.md
We really needed a link off the front page to get to the releases.
=> added in releases link

CHANGELOG.md, ansible/roles/bootstrap/tasks/main.yml, docs/deployment.md
Overlays for usbhost0-3 exist by default (but are still not
enabled) so we no longer need to pin related packages or setup
the usbhost1 ourselves.
This requires our NEO armbian builds to be based off https://github.com/ConnectBox/armbian-build/releases/tag/base-image-180408 or newer
Fixes #149 #224
=> Move to armbian mainline 4.14

ansible/group_vars/armbian, ansible/roles/bootstrap/tasks/main.yml
The @reboot job in the cron.d file is causing dpkg locking contention after reboot.
Fixes #214
=> Disable internal armbian update process

CHANGELOG.md, ansible/roles/connectbox-pi/files/sshswitch.service, ansible/roles/connectbox-pi/handlers/main.yaml, ansible/roles/connectbox-pi/tasks/main.yml, docs/deployment.md, docs/development.md
ssh is now disabled on all pre-made connectbox images. To enable it, create a file called .connectbox/enable-ssh on the USB storage, insert it and reboot.
=> Jit development mode

CHANGELOG.md, python/captive_portal/manager.py, tests/test_connectbox_static.py
Make the captive portal browser stay open so users can read instructions
Switch to hrefs instead of text URLs on macOS 10.13 and iOS 11
=> Android 7 cp fix

ansible/roles/bootstrap/tasks/main.yml
This might be brutish, but we do want to give the command line
tools some locale so that it doesn't spit errors on the screen
when running perl or trying to create python virtualenvs
=> Set locale

ansible/roles/usb-content/tasks/main.yml
We weren't using a systemd drop-in, so the MountFlags were getting overwritten when packages were updated.
=> Fix USB mounting on rasbpian when packages are updated

CHANGELOG.md, ansible/roles/wifi-ap/templates/hostapd.conf.j2
non-OFDM rates use a disproportionately large amount of airtime
and aren't needed by modern clients, so let's disabled them in
order to have more airtime available when there are clients on
a network that have a poor connection
Closes #116
=> Disable non-OFDM Wifi rates

ansible/roles/image-preparation/tasks/main.yml, ansible/roles/neo-battery-tools/templates/neo-battery-shutdown.service.j2
libfreetype is needed for OLED HATs. Don't remove it.
=> Add libfreetype. Start hat service earlier

ansible/roles/wifi-ap/templates/configure_hostapd.sh.j2, ansible/roles/wifi-ap/templates/hostapd.conf.j2
The forced sync is as a precaution against filesystem corruption that we've seen where hostapd.conf has unrelated content.
=> Conditionally activate 802.11ac and force sync hostapd

ansible/roles/wifi-ap/tasks/main.yml, python/admin/api.py
* wifi-configurator now sets it automatically
* add crda package so regdb is always available (req. for wifi configurator)
=> Don't allow channel to be set from admin UI
