- .travis.yml
- README.md
- requirements.txt
Use a common definition between dev and CI test for the version of ansible and ansible-lint
> Define working environment

- ansible/roles/dns-dhcp/tasks/main.yml
- ci/script_run_on_non_pull_requests.sh
Fix DNS - it was broken after dnsmasq was installed. Perform a second provision task in the CI pipeline to demonstrate that it's working now.
> Fix broken dns

- ansible/roles/dns-dhcp/defaults/main.yml
- ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2
This implements the solution described in @mattpascoe 's https://github.com/edwinsteele/biblebox-pi/pull/7 .
> Dont store dhcp lease info

- ansible/group_vars/all
- ansible/roles/webserver-content/files/success.html
- ansible/roles/webserver-content/tasks/main.yml
- tests/test_connectbox_static.py
Android/Windows behaviour captured in https://github.com/edwinsteele/biblebox-pi/issues/41
> Fix iOS/MacOS captive portal behaviour

- html/admin/css/style.css
- html/admin/index.html
- html/admin/js/connectbox-ui.js
- scripts/ConnectBoxManage.sh
- tests/test_connectbox_static.py
> Add a check for the length of the ssid in bytes

- .travis.yml
- ci/script_run_on_non_pull_requests.sh
- Bump terraform to 0.8.2
- Fix codacy lint warning
> Add extra debugging to help diagnose stuck builds

- docs/administration.md
- docs/deployment.md
- docs/development.md
> Update doco for current raspbian

- README.md
- ansible/group_vars/all
- ansible/roles/webserver-content/files/ncsi.txt
- ansible/roles/webserver-content/files/wifistub.html
- ansible/roles/webserver-content/tasks/main.yml
- tests/test_connectbox_static.py
I don’t have any android devices, so feedback is helpful (@geodirk @K7TRY , perhaps you can test this in the device lab?)
Please list the device/os ver you used for validation in comments, if possible.
Partial fix for #41
> Fix android captive portal

- README.md
- ansible/group_vars/all
- ansible/group_vars/pine64
- ansible/inventory.example
- docs/deployment.md
- docs/development.md
Update documentation so it's no longer specific for the Raspberry Pi
> Add Pine64 support and update doco for Armbian

- Vagrantfile
- ansible/roles/bootstrap/tasks/main.yml
- ansible/roles/connectbox-pi/tasks/main.yml
Randoms. No functional change.
> Randoms - vagrantfile fix, reduced change count on rerun, detect wlan0 nicely

- docs/deployment.md
- tests/test_connectbox_static.py
Fixes #84 
(Also adds warning against using Armbian Ubuntu Xenial images, even though it's an unrelated change)
> Bugfix ssid test idempotency

- ansible/roles/usb-content/files/etc_usbmount_usbmount.conf
- ansible/roles/usb-content/handlers/main.yml
- ansible/roles/usb-content/tasks/main.yml
USB keys were not showing UTF-8 characters (found by Kirk Wilson)
> Fix usb mount args

- html/admin/api.php
- html/admin/index.html
- html/admin/js/connectbox-ui.js
- scripts/ConnectBoxManage.sh
Here's the integration with the admin dashboard for static site toggle
> Admin ui static siteconfig

- ansible/roles/bootstrap/tasks/main.yml
> Disable unattended upgrades

- ansible/group_vars/all
- ansible/roles/dns-dhcp/defaults/main.yml
- html/captive_portal/captive_portal_manager.py
This makes it easier to do reasonably accurate but anonymised
session counting
> Use /16 instead of /24 for DHCP and give 24h lease

- ansible/group_vars/ar9271
- ansible/group_vars/pine64
- ansible/group_vars/rt5370
- ansible/group_vars/rt5372
- ansible/group_vars/rtl8192cu
- ansible/roles/wifi-ap/defaults/main.yml
> Don't allow 40Mhz channels due to perf degradation

- ansible/roles/nginx/templates/connectbox_captive-portal.conf.j2
- html/captive_portal/captive_portal_manager.py
- html/captive_portal/templates/connected.html
- tests/test_connectbox_static.py
> Add Android 5 captive portal workflow

- Vagrantfile
- ansible/group_vars/all
- ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2
- ci/main.tf
- requirements.in
- requirements.txt
- tests/test_connectbox_static.py
> Direct samsung devices through the captive portal

- ansible/roles/bootstrap/tasks/main.yml
- ansible/roles/connectbox-pi/meta/main.yml
- ansible/roles/neo-battery-tools/defaults/main.yml
- ansible/roles/neo-battery-tools/handlers/main.yml
- ansible/roles/neo-battery-tools/tasks/main.yml
- ansible/roles/neo-battery-tools/templates/neo-battery-shutdown.service.j2
- ansible/roles/neo-battery-tools/templates/pa6-pulldown.service.j2
- ansible/roles/neo-battery-tools/vars/main.yml
Only install tool on NanoPi NEO devices
Hoist installation of git and virtualenv tools to the bootstrap role
Fixes #192
> Install & activate neo battery level shutdown tool

- CHANGELOG.md
- html/admin/index.html
> Admin tweaks

- html/admin/index.html
- python/templates/connected.html
Small UI nits to change from my testing.
> mods to the UI

- ansible/roles/bootstrap/files/armhwinfo
- ansible/roles/bootstrap/tasks/main.yml
> Fix corrupted armbian env

- ansible/roles/webserver-content/tasks/main.yml
- python/chat/server.py
- python/requirements.dev.txt
- tests/test_connectbox_static.py
> Captive portal chat to py3

- ansible/roles/bootstrap/tasks/main.yml
These workarounds are now in base-image-180416
> Remove upstreamed armbian workarounds

- ansible/group_vars/all
- ansible/roles/connectbox-pi/handlers/main.yaml
- ansible/roles/connectbox-pi/tasks/main.yml
- ansible/roles/webserver-content/tasks/main.yml
- ci/script_run_on_non_pull_requests.sh
- python/main.py
- scripts/ConnectBoxManage.sh
- tests/test_connectbox_static.py
Also:
* Clarify test hosts during CI
* Fix noise during some admin actions due to gunicorn hosting both captive portal and admin API
* Add static site API test to improve coverage based on python API migration
Resolves #111 
FYI @portablejim @kldavis4
> Complete removal of PHP

- CHANGELOG.md
- ansible/group_vars/all
- ansible/roles/connectbox-pi/tasks/main.yml
- ansible/roles/neo-battery-tools/tasks/main.yml
Also includes build number capture
Ahead of the merge of https://github.com/ConnectBox/NEO_BatteryLevelShutdown/pull/4
> axp209 and OLED supporting system changes

- CHANGELOG.md
- ansible/roles/bootstrap/tasks/main.yml
This reapplies logic from #218
> Fix package holds, working around aptitude's behaviour

- python/captive_portal/manager.py
- python/main.py
- python/templates/connected.html
- tests/test_connectbox_static.py
Hopefully addresses #245 and the same issue that manifests on Android 7.
> Android 8 captive portal

- python/captive_portal/manager.py
- tests/test_connectbox_static.py
Android 7+ CPAs are dalvik
Provide a shorter timeout to help with testing
> Provide 204s to Android 7+ CPAs

- ansible/group_vars/all
- ansible/roles/dns-dhcp/templates/etc_dnsmasq.conf.j2
- ansible/roles/network-interfaces/templates/etc_network_interfaces.j2
Clean up templating for non-private CP address
Remove DNAT'ing as the additional IP makes it redundant
> Add IP for non-private android CP address to wlan0

- ansible/roles/image-preparation/tasks/main.yml
> Don't purge other packages on raspbian

- ansible/group_vars/brand
- ansible/roles/bootstrap/tasks/main.yml
- ansible/roles/bootstrap/templates/brand_txt.j2
- ansible/site.yml
- scripts/ConnectBoxManage.sh
- scripts/phonehome.py
1. Add settings to brand.txt template
2. Create script phonehome.py that will send status and get settings changes
3. Update ConnectBoxManage.sh to handle brand.txt changes except the LCD page display array
> Initial Check-In for Connectbox

- python/admin/api.py
"openwell-download", "moodle_download" should be modified as "set openwell-download" and not "set brand openwell-download". Same is true from "moodle_download"
> Change wrong routes for download props

- ansible/group_vars/all
- ansible/roles/bootstrap/tasks/main.yml
- ansible/roles/enhanced-content/files/bin_connectboxmanage
- ansible/roles/enhanced-content/tasks/main.yml
- scripts/phonehome.py
Let's have a meeting together this coming week to review
1. Install connectbox-manage to /var/www/enhanced/connectbox-manage
2. Install nodejs process manager pm2 to manage the API application 
3. Enable the management to be run from command line: connectboxmanage
See the repo at https://github.com/RT-coding-team/connectbox-manage
Does not remove the existing ConnectBoxManage.sh nor api.py but configures nginx and tools to the new script.
> Newconnectboxmanage
